export const products = [
  {
    type: "dogsFood",
    imageUrl: "https://i.imgur.com/xRb3BQK.jpg",
    imageText: "Pacote de ração da marce Pedrigree",
    figureCaption: "Ração Seca Pedrigree",
    category: "Carnes e Vegetais",
    baseValue: 194.79,
    promotionalValue: 175.31,
  },
  {
    type: "toys",
    imageUrl: "https://i.imgur.com/aFzzCYZ.jpg",
    imageText: "Nicho para gatos",
    figureCaption: "Nicho para gatos Play kit",
    category: "",
    baseValue: 199.9,
  },
  {
    type: "fishProducts",
    imageUrl: "https://i.imgur.com/HE6FNb3.jpg",
    imageText: "Bacterecida Atlantys 15ml",
    figureCaption: "Bacterecida Atlantys",
    category: "Peixes 15ml",
    baseValue: 29.99,
  },
  {
    type: "dogsFood",
    imageUrl: "https://i.imgur.com/9SVvuZM.jpg",
    imageText: "Pacote ração royal canin 20kg",
    figureCaption: "Royal Canin",
    category: "Digestive Care ",
    baseValue: 392.99,
  },
  {
    type: "dogsFood",
    imageUrl: "https://i.imgur.com/MWDmEN7.jpg",
    imageText: "Pacote ração Golden Formula Cães Adultos Raças pequenas 10,1kg",
    figureCaption: "Golden Formula",
    category: "Frango e Arroz 10,1kg",
    baseValue: 113.9,
  },
  {
    type: "dogsFood",
    imageUrl: "https://i.imgur.com/EkZCK9a.jpg",
    imageText: "Pacote ração Food Dog Adulto Manutenção 500g",
    figureCaption: "Food Dog Manutenção",
    category: "Cães adultos 500g",
    baseValue: 175.99,
  },
  {
    type: "catsFood",
    imageUrl: "https://i.imgur.com/ZEj9bfA.jpg",
    imageText: "Ração gato natural 7,5kg",
    figureCaption: "Ração Gato Castrado",
    category: "Frango e arroz 7,5kg",
    baseValue: 199.9,
  },
  {
    type: "catsFood",
    imageUrl: "https://i.imgur.com/jvXauH1.jpg",
    imageText: "Ração gato Whiskas Carne ",
    figureCaption: "Ração Whiskas",
    category: "Carne 10,1kg 1+ano",
    baseValue: 160.3,
    promotionalValue: 144.27,
  },
  {
    type: "catsFood",
    imageUrl: "https://i.imgur.com/sObw1tf.jpg",
    imageText: "Ração gato GranPlus Adulto 10,1kg",
    figureCaption: "Ração GranPlus Choice",
    category: "Frango e Carne 10,1kg",
    baseValue: 97.6,
  },
  {
    type: "catsFood",
    imageUrl: "https://i.imgur.com/FTI6A7r.jpg",
    imageText: "Ração Seca PremieR Adultos Castrados 6kg",
    figureCaption: "Ração Seca PremieR Pet",
    category: "Castrados Salmão",
    baseValue: 110.9,
    promotionalValue: 99.81,
  },
  {
    type: "fishProducts",
    imageUrl: "https://i.imgur.com/acvIygl.jpg",
    imageText: "Aquário Boyo Curvo 472 litros",
    figureCaption: "Aquário Boyu Curvo 472L",
    category: "Pretro Champagne",
    baseValue: 6199.99,
  },
  {
    type: "fishProducts",
    imageUrl: "https://i.imgur.com/HE6FNb3.jpg",
    imageText: "Bacterecida Atlantys 15ml",
    figureCaption: "Bacterecida Atlantys",
    category: "Para Peixes 15ml",
    baseValue: 29.99,
  },
  {
    type: "fishProducts",
    imageUrl: "https://i.imgur.com/vTTvlwt.jpg",
    imageText: "Aquário Boyo Curvo 246 litros",
    figureCaption: "quário Boyu Curvo 246L",
    category: "Pretro Champagne",
    baseValue: 3599.99,
  },
  {
    type: "fishProducts",
    imageUrl: "https://i.imgur.com/LA8Qkyc.jpg",
    imageText: "Carvão Ativado Para Aquários AC",
    figureCaption: "Carvão Ativado Peletizado",
    category: "Para Aquários AC",
    baseValue: 20.9,
  },
  {
    type: "toys",
    imageUrl: "https://i.imgur.com/9uogJmx.jpg",
    imageText: "Brinquedo mordedor cachorro de Cenoura e graveto",
    figureCaption: "Mordedor Buddy Toys",
    category: "Cenoura e Graveto",
    baseValue: 74.68,
  },
  {
    type: "toys",
    imageUrl: "https://i.imgur.com/LoSkae7.jpg",
    imageText: "Nicho para gatos",
    figureCaption: "Nicho De Gatos MDF",
    category: "Play Kit 10 peças",
    baseValue: 199.9,
  },
  {
    type: "toys",
    imageUrl: "https://i.imgur.com/K61EUJy.jpg",
    imageText: "Brinquedo gato Varinha Azul",
    figureCaption: "Varinha Cat",
    category: "Fishing Azul",
    baseValue: 13.32,
  },
  {
    type: "toys",
    imageUrl: "https://i.imgur.com/Ssouh3c.jpg",
    imageText: "Brinquedo Cachorro RedonDog",
    figureCaption: "Brinquedo Pet Games",
    category: "Interativo RedonDog",
    baseValue: 20.17,
  },
];
